{"data":[{"message":"My terminal is not giving the normal \"...ok\" or \"...fail\" either but I have begun my test cases with \"test_\". I am also calling unittest.main()","id":"846180025485253_927080514061870","comments":{"data":[{"created_time":"2017-04-02T22:26:09+0000","from":{"name":"Dani Newport","id":"744500918992774"},"message":"delete the unittest.main(), i did the same thing but after i removed that my tests ran fine","id":"927083424061579"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTURnek5ESTBNRFl4TlRjNU9qRTBPVEV4TnpFNU5qaz0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTURnek5ESTBNRFl4TlRjNU9qRTBPVEV4TnpFNU5qaz0ZD"}}}},{"message":"wait does every question have to say ok....or are 9 and 10 supposed to say error..?","id":"846180025485253_927196644050257","comments":{"data":[{"created_time":"2017-04-03T02:05:13+0000","from":{"name":"Nate Baker","id":"576403122467319"},"message":"for 9, you're suppose to expose one bug, so yes a failure, and for ten you're supposed to expose both bugs, so yes failure","id":"927199560716632"},{"created_time":"2017-04-03T02:05:33+0000","from":{"name":"Austin Kent","id":"1074330132577828"},"message":"ok so will it say error or fail?","id":"927199714049950"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTVRrNU5UWXdOekUyTmpNeU9qRTBPVEV4T0RVeE1UUT0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTVRrNU56RTBNRFE1T1RVd09qRTBPVEV4T0RVeE16TT0ZD"}}}},{"message":"Is PS10 number 10 supposed to return an Error??","id":"846180025485253_927204270716161","comments":{"data":[{"created_time":"2017-04-03T02:27:54+0000","from":{"name":"Dani Newport","id":"744500918992774"},"message":"if you write the tests correctly, you should be getting the \"FAIL\" message for two of the methods","id":"927208390715749"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTWpBNE16a3dOekUxTnpRNU9qRTBPVEV4T0RZAME56UT0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTWpBNE16a3dOekUxTnpRNU9qRTBPVEV4T0RZAME56UT0ZD"}}}},{"message":"does anyone know what im doing wrong here?","id":"846180025485253_927165380720050","comments":{"data":[{"created_time":"2017-04-03T01:15:59+0000","from":{"name":"Ling Wen Hoong","id":"10201836494017807"},"message":"Not sure if this is the cause, but the type for get_airport should be a dictionary instead of string. You should use key in type({}) instead of 'str'","id":"927167620719826"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTVRZAM05qSXdOekU1T0RJMk9qRTBPVEV4T0RJeE5qQT0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTVRZAM05qSXdOekU1T0RJMk9qRTBPVEV4T0RJeE5qQT0ZD"}}}},{"message":"For PS10, Problem 9, the error seems to be an indexing error in blackbox.py. My unittest catches this, but since the function crashes, my unittest returns an \"ERROR\" instead of a \"FAIL\". \nIs that okay? Instructors?","id":"846180025485253_923500117753243","likes":{"data":[{"id":"737500542955260","name":"Suhas Maganti"},{"id":"776002462438243","name":"Sam Ansara"},{"id":"10204851415278538","name":"Brian Huang"}],"paging":{"cursors":{"before":"NzM3NTAwNTQyOTU1MjYw","after":"MTAyMDQ4NTE0MTUyNzg1MzgZD"}}},"comments":{"data":[{"created_time":"2017-04-03T01:53:36+0000","from":{"name":"Alexa Sonnenblick","id":"1469286970004307"},"message":"did you find out if this was ok?","id":"927185187384736"},{"created_time":"2017-04-03T02:11:46+0000","from":{"name":"Preet Patel","id":"10202866425765241"},"message":"Yeah, it is","id":"927202454049676"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTVRnMU1UZAzNNemcwTnpNMk9qRTBPVEV4T0RRME1UYz0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTWpBeU5EVTBNRFE1TmpjMk9qRTBPVEV4T0RVMU1EYz0ZD"}}}},{"message":"Why is the except  term giving a syntax error","id":"846180025485253_927122777390977","comments":{"data":[{"created_time":"2017-04-03T00:23:38+0000","from":{"name":"Nisa Khan","id":"10211805796797886"},"message":"this happened to me too! and a couple of others-- you just have to backspace and forward a couple of times. it's very strange.","id":"927133397389915"},{"created_time":"2017-04-03T02:03:26+0000","from":{"name":"Tsuyoshi Kano","id":"841990612544174"},"message":"I agree Nisa's suggestion. I guess this is due to invisible characters such as space, tab, and new line character.","id":"927197167383538"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTVRNek16azNNemc1T1RFMU9qRTBPVEV4Tnprd01Uaz0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTVRrM01UWTNNemd6TlRNNE9qRTBPVEV4T0RVd01EWT0ZD"}}}},{"message":"can someone please help me with numero 3?","id":"846180025485253_927098857393369","comments":{"data":[{"created_time":"2017-04-02T23:08:12+0000","from":{"name":"Dani Newport","id":"744500918992774"},"message":"assign your instance of card (the line under your def) to a variable to be called in assertEqual, as when you are calling it as \"self.assertEqual(str(Card), '3')\", Card is a class NOT an instance: so when you assign a variable to your instance, call that variable name in the last line instead of \"Card\"","id":"927099680726620"},{"created_time":"2017-04-02T23:13:17+0000","from":{"name":"Austin Kent","id":"1074330132577828"},"message":"ok thanks","id":"927101557393099"},{"created_time":"2017-04-02T23:18:33+0000","from":{"name":"Austin Kent","id":"1074330132577828"},"message":"","id":"927103710726217"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTURrNU5qZA3dOekkyTmpJd09qRTBPVEV4TnpRME9UST0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTVRBek56RXdOekkyTWpFM09qRTBPVEV4TnpVeE1UTT0ZD"}}}},{"message":"anyone know why this is happening? i've downloaded black_box.py into the same folder that my problem set is in pls help","id":"846180025485253_927143784055543","likes":{"data":[{"id":"10203409293089137","name":"Maxwell Harris Frenkel"},{"id":"727479887329657","name":"Jessica Vu"}],"paging":{"cursors":{"before":"MTAyMDM0MDkyOTMwODkxMzcZD","after":"NzI3NDc5ODg3MzI5NjU3"}}},"comments":{"data":[{"created_time":"2017-04-03T01:18:04+0000","from":{"name":"Grace Badagliacca","id":"850472771692991"},"message":"did you figure out how to fix this?","id":"927168537386401"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTVRZANE5UTTNNemcyTkRBeE9qRTBPVEV4T0RJeU9EUT0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTVRZANE5UTTNNemcyTkRBeE9qRTBPVEV4T0RJeU9EUT0ZD"}}}},{"message":"If we are going to do one of the pre specified projects for the final project we don't have to send an email saying which one we picked right?","id":"846180025485253_927156380720950","comments":{"data":[{"created_time":"2017-04-03T00:52:41+0000","from":{"name":"David Nguyen","id":"668470416521759"},"message":"that's correct!","id":"927156570720931"},{"created_time":"2017-04-03T00:52:56+0000","from":{"name":"Preet Patel","id":"10202866425765241"},"message":"You will have to mention that in the last ques in PS11","id":"927156654054256"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTVRVMk5UY3dOekl3T1RNeE9qRTBPVEV4T0RBM05qRT0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTVRVMk5qVTBNRFUwTWpVMk9qRTBPVEV4T0RBM056Yz0ZD"}}}},{"id":"846180025485253_926891157414139"},{"message":"Could anyone help me with this error. It didn't shows ok or fail. Thanks a lot","id":"846180025485253_927095217393733","comments":{"data":[{"created_time":"2017-04-02T23:01:17+0000","from":{"name":"David Nguyen","id":"668470416521759"},"message":"did you also download the black_box.py file from canvas and put it in the same directory?","id":"927097054060216"},{"created_time":"2017-04-02T23:12:37+0000","from":{"name":"Vicky Guo","id":"678182135692104"},"message":"thank you so much indeed. I have fixed it.","id":"927101337393121"},{"created_time":"2017-04-02T23:37:32+0000","from":{"name":"Drew Sisson","id":"855174051236974"},"message":"How did you go about fixing this? I can't seem to get them in the same directory","id":"927112244058697"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTURrM01EVTBNRFl3TWpFMk9qRTBPVEV4TnpRd056Yz0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTVRFeU1qUTBNRFU0TmprM09qRTBPVEV4TnpZAeU5UST0ZD"}}}},{"message":"Anyone know whats good with this? I didn't change the requests for the airport.","id":"846180025485253_927109137392341"},{"message":"Are these codes acceptable for question 10? First one runs second one gives an error.","id":"846180025485253_925466207556634","comments":{"data":[{"created_time":"2017-04-02T22:49:47+0000","from":{"name":"Nisa Khan","id":"10211805796797886"},"message":"i think these are suppose to pass!","id":"927092337394021"},{"created_time":"2017-04-02T23:14:16+0000","from":{"name":"Jasmine Smith","id":"1056517051054983"},"message":"It said one should return an error","id":"927101980726390"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTURreU16TTNNemswTURJeE9qRTBPVEV4TnpNek9EZAz0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTVRBeE9UZA3dOekkyTXprd09qRTBPVEV4TnpRNE5UWT0ZD"}}}},{"message":"Does anyone know if the 'list index out of range' for problem 9 in PS10 is correct? Because every other question the tests just fail but in this instance there is an error. Also I had three tests fail for problem 10 and it says there are only 2 bugs, did anyone else experience that?","id":"846180025485253_927063917396863","comments":{"data":[{"created_time":"2017-04-02T22:01:53+0000","from":{"name":"Nate Baker","id":"576403122467319"},"message":"i have no idea what your first question means, but i only exposed two bugs. They were in the first and third methods of that class.","id":"927074080729180"},{"created_time":"2017-04-02T22:09:30+0000","from":{"name":"Nate Baker","id":"576403122467319"},"message":"Oh, I think I got an Error as well","id":"927077100728878"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTURjME1EZA3dOekk1TVRnd09qRTBPVEV4TnpBMU1UTT0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTURjM01UQXdOekk0T0RjNE9qRTBPVEV4TnpBNU56QT0ZD"}}}},{"message":"For the DarkSky Net project, does caching need to persist over multiple sessions? Or do we clear the cache after the user exits?","id":"846180025485253_927087304061191"},{"message":"could anyone help me about the problem 7. I am not sure what happened with my backspace there? or about the \"except part? Do I need to write anything instead? \n\nThanks","id":"846180025485253_927083634061558"},{"message":"I'm not sure what exactly #7 #8 on PS 10 is asking. This is what I have right now...but I don't know exactly how to call the function in 8 or if the function in 7 is written correctly. Any input would be awesome, thank you!","id":"846180025485253_927064774063444","likes":{"data":[{"id":"744500918992774","name":"Dani Newport"}],"paging":{"cursors":{"before":"NzQ0NTAwOTE4OTkyNzc0","after":"NzQ0NTAwOTE4OTkyNzc0"}}},"comments":{"data":[{"created_time":"2017-04-02T21:54:48+0000","from":{"name":"Nate Baker","id":"576403122467319"},"message":"problem 7 looks correct, but for 8 just make test cases for what the output suppose to do.","id":"927070877396167"},{"created_time":"2017-04-02T21:56:03+0000","from":{"name":"Nate Baker","id":"576403122467319"},"message":"btw, i would test the type returned if you pass in the string \"DTW\" because it will give a dictionary","id":"927071474062774"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTURjd09EYzNNemsyTVRZAM09qRTBPVEV4TnpBd09EZAz0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTURjeE5EYzBNRFl5TnpjME9qRTBPVEV4TnpBeE5qUT0ZD"}}}},{"id":"846180025485253_924822704287651","comments":{"data":[{"created_time":"2017-04-02T21:20:05+0000","from":{"name":"\u59dc\u6615\u6615","id":"446448239031991"},"message":"what if I put like Deck(0,51) instead of Deck(), I checked for that , but it doesn't work","id":"927054377397817"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTURVME16YzNNemszT0RFM09qRTBPVEV4Tmpnd01EVT0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTURVME16YzNNemszT0RFM09qRTBPVEV4Tmpnd01EVT0ZD"}}}},{"message":"can anyone help me for problem 9. it says \n\nTraceback (most recent call last):\n  File \"\/Users\/eddahanafi\/Desktop\/106\/ps10.py\", line 217, in test9\n    self.assertEqual(mySum([]), 0 , \"Not right\")\n  File \"\/Users\/eddahanafi\/Desktop\/106\/black_box.py\", line 9, in mySum\n    else: return a[range(1)[0]] + mySum(a[1:])\nIndexError: list index out of range\n\n----------------------------------------------------------------------\nRan 7 tests in 0.002s\n\nFAILED (errors=1)","id":"846180025485253_924842297619025","likes":{"data":[{"id":"10201836494017807","name":"Ling Wen Hoong"}],"paging":{"cursors":{"before":"MTAyMDE4MzY0OTQwMTc4MDcZD","after":"MTAyMDE4MzY0OTQwMTc4MDcZD"}}},"comments":{"data":[{"created_time":"2017-03-31T02:25:13+0000","from":{"name":"Ling Wen Hoong","id":"10201836494017807"},"message":"It does say in the question that one of our tests should fail as the function mySum is buggy","id":"924854424284479"},{"created_time":"2017-03-31T02:25:33+0000","from":{"name":"Ling Wen Hoong","id":"10201836494017807"},"message":"I got the same result as you btw","id":"924854594284462"},{"created_time":"2017-03-31T02:32:30+0000","from":{"name":"Edda Nadira Hanafi","id":"4429325349416"},"message":"So does that mean this is correct?? Haha","id":"924857437617511"},{"created_time":"2017-04-02T21:01:22+0000","from":{"name":"Julian Bennett","id":"911460758888444"},"message":"Did you guys figure out if this was right?","id":"927045184065403"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkwT0RVME5ESTBNamcwTkRjNU9qRTBPVEE1TWpjeE1UTT0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTURRMU1UZAzBNRFkxTkRBek9qRTBPVEV4TmpZANE9EST0ZD"}}}},{"message":"Could anyone find what's  wrong with my problem 4 here? I write code like this but I don't understand what is the meaning of the error code here?\n\nOr do I need the other way to write suit??\nThanks!","id":"846180025485253_927019457401309","comments":{"data":[{"created_time":"2017-04-02T20:13:59+0000","from":{"name":"Jaime Chusid","id":"1106572406020306"},"message":"U need a colon after defining a class","id":"927023004067621"},{"created_time":"2017-04-02T20:16:14+0000","from":{"name":"Nisa Khan","id":"10211805796797886"},"message":"I feel like you should be using assert too!","id":"927023967400858"},{"created_time":"2017-04-02T20:52:06+0000","from":{"name":"\u59dc\u6615\u6615","id":"446448239031991"},"message":"I had fixed that ! Thank you guys so much. I use the assertEqual at last","id":"927041300732458"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTURJek1EQTBNRFkzTmpJeE9qRTBPVEV4TmpRd016az0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkzTURReE16QXdOek15TkRVNE9qRTBPVEV4TmpZAek1qYz0ZD"}}}},{"message":"If 10a passes and 10b fails, does that mean I did it correctly?","id":"846180025485253_927016957401559","likes":{"data":[{"id":"911460758888444","name":"Julian Bennett"}],"paging":{"cursors":{"before":"OTExNDYwNzU4ODg4NDQ0","after":"OTExNDYwNzU4ODg4NDQ0"}}}},{"message":"For the final project,\n1) Do I code in 2.x or 3.x?\n2) Does human player must be the first one to entry guesses?\nThanks!","id":"846180025485253_927003930736195"},{"message":"Does anyone know why my terminal is not giving the normal \"...ok\"\/\"...fail\" messages? :-))","id":"846180025485253_926977590738829","comments":{"data":[{"created_time":"2017-04-02T18:52:49+0000","from":{"name":"Paul Green","id":"472697816210993"},"message":"You have to begin your test functions with \"test_\"","id":"926978827405372"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkyT1RjNE9ESTNOREExTXpjeU9qRTBPVEV4TlRreE56QT0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkyT1RjNE9ESTNOREExTXpjeU9qRTBPVEV4TlRreE56QT0ZD"}}}},{"message":"The error is telling me I have something wrong with my indentation but I've tried everything and can't find the proper spacing\/indentation. Can someone help?","id":"846180025485253_926891154080806","comments":{"data":[{"created_time":"2017-04-02T17:04:56+0000","from":{"name":"Nate Baker","id":"576403122467319"},"message":"backspace from the line with the except command to the line with requests.get command and then press enter. That helped me.","id":"926915014078420"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkyT1RFMU1ERTBNRGM0TkRJd09qRTBPVEV4TlRJMk9UYz0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkyT1RFMU1ERTBNRGM0TkRJd09qRTBPVEV4TlRJMk9UYz0ZD"}}}},{"message":"when i am compiling the code, i am having trouble seeing if i am passing anything? there is no \"ok\" or checks that i am passing the tests. does anyone know what i might be doing wrong?","id":"846180025485253_926558850780703","comments":{"data":[{"created_time":"2017-04-02T06:02:40+0000","from":{"name":"David Nguyen","id":"668470416521759"},"message":"did you make sure you had your test cases begin with \"test_\"?","id":"926559734113948"}],"paging":{"cursors":{"before":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkyTlRVNU56TTBNVEV6T1RRNE9qRTBPVEV4TVRJNU5qQT0ZD","after":"WTI5dGJXVnVkRjlqZAFhKemIzSTZAPVEkyTlRVNU56TTBNVEV6T1RRNE9qRTBPVEV4TVRJNU5qQT0ZD"}}}}],"paging":{"previous":"https:\/\/graph.facebook.com\/v2.8\/846180025485253\/feed?fields=message,comments,likes&icon_size=16&since=1491198093&access_token=EAACEdEose0cBAFiMXMLIihbPHzm33LV3ZCOPWYX4ysifAXMpyrZBiZC7wQ3T2emjXhJVM52LZBDcF5r8dKCUB6Wdz5p9G6zGuCjwt79ov3ifujEqXBZCSwOigYHrPDyjxDytr4wY1TIZCjkZBgWTr8bQa1IBIsftccmO0JFbFVgGesdju8KIXljo4y0hZCmGQgcZD&limit=25&__paging_token=enc_AdAUMj0wqLTTvIHL72v9uqsweTNxaCQ1EWwRrkkzyZAttZCUHLXv86c109jqdT7mceRfIoYLJa7wlrkRkNG2LjEry2nqGGQt60A55yaj4Y5r9k9gZDZD&__previous=1","next":"https:\/\/graph.facebook.com\/v2.8\/846180025485253\/feed?fields=message,comments,likes&icon_size=16&access_token=EAACEdEose0cBAFiMXMLIihbPHzm33LV3ZCOPWYX4ysifAXMpyrZBiZC7wQ3T2emjXhJVM52LZBDcF5r8dKCUB6Wdz5p9G6zGuCjwt79ov3ifujEqXBZCSwOigYHrPDyjxDytr4wY1TIZCjkZBgWTr8bQa1IBIsftccmO0JFbFVgGesdju8KIXljo4y0hZCmGQgcZD&limit=25&until=1491152470&__paging_token=enc_AdAZAGL9iXW4AnZAM6iOEKiDCXofNLPMxl0J1G7SSoeydFS5wQ26e7g3KYUpXnsoN73XnZCBjVV6MA4A8OYnyPlzp85aUF0V7iYPk3IzR3xZCGBuKAZDZD"}}